// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace WebScraper.ScraperApi.Models
{
    /// <summary>
    /// Multiple Response Types V1WikipicsUriTagGetOKResponseContent, V1WikipicsUriTagGetAcceptedResponseContent, V1WikipicsUriTagGetBadRequestResponseContent
    /// </summary>
    public partial class MultipleV1WikipicsUriTagGet
    {
        

        /// <summary>
        /// Return scraping results for provided url and html tag combination. 
        /// </summary>

        public V1WikipicsUriTagGetOKResponseContent V1WikipicsUriTagGetOKResponseContent { get; set; }

        /// <summary>
        /// Scraping task for requested wiki url and tag is already scheduled. Results are not available yet. 
        /// </summary>

        public V1WikipicsUriTagGetAcceptedResponseContent V1WikipicsUriTagGetAcceptedResponseContent { get; set; }

        /// <summary>
        /// Provided url or url to scrape is not valid. 
        /// </summary>

        public V1WikipicsUriTagGetBadRequestResponseContent V1WikipicsUriTagGetBadRequestResponseContent { get; set; }
    } // end class

} // end Models namespace

