// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using WebScraper.ScraperApi.Models;

// Do not modify this file. This code was generated by RAML Server Scaffolder

namespace WebScraper.ScraperApi
{
    [RoutePrefix("v1/wikipics/{uri}/{tag}")]
    public partial class V1WikipicsUriTagController : ApiController
    {


/// <summary>
		/// Scrape provided web url and html tag and return resutls. - /v1/wikipics/{uri}/{tag}
		/// </summary>
		/// <param name="uri">Wiki url.</param>
		/// <param name="tag">A valid html tag (case-insensative).</param>
		/// <returns>MultipleV1WikipicsUriTagGet</returns>
        [ResponseType(typeof(MultipleV1WikipicsUriTagGet))]
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase([FromUri] string uri,[FromUri] string tag)
        {
            // Do not modify this code
                        return  ((IV1WikipicsUriTagController)this).Get(uri,tag);
                    }
    }
}
