// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace WebScraper.ScraperApi.Models
{
    public partial class V1WikipicsUriTagGetBadRequestResponseContent
    {
        


        public string Status { get; set; }
    } // end class

} // end Models namespace

